# Generated by Django 5.2.1 on 2025-05-26 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="title",
            field=models.CharField(
                default="example",
                help_text="Enter a title for the book",
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, message="title of book should be 3 characters or longer"
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="length",
            field=models.IntegerField(
                help_text="Enter the amount of pages this book has to offer"
            ),
        ),
    ]
